### ISSUE TITLE
Confusion over adding support for MultiArchUefiPkg into a project

### ISSUE THREAD

**Issue by ghost** [intel/MultiArchUefiPkg#26]
I'm confused about how to go about adding support for MultiArchUefiPkg into a project. https://github.com/intel/MultiArchUefiPkg/blob/main/Docs/Building.md has instructions, and details options like SUPPORTS_X64_BINS.

But, SUPPORTS_X64_BINS only appears to be an applicable option for Emulator.dsc, not platforms like ArmVirtPkg because elsewhere the option for building X64 binary support is referred to as MAU_SUPPORTS_X64_BINS.

I attempted to work around this by adding the following in to my platform's .dsc file:
```
  ON_PRIVATE_STACK               = NO
  WRAPPED_ENTRY_POINTS           = NO
  CHECK_ORPHAN_CONTEXTS          = NO
  EMU_TIMEOUT_NONE               = NO
  SUPPORTS_X64_BINS              = YES
  UPPORTS_AARCH64_BINS           = NO
  EMU_X64_RAZ_WI_PIO             = YES
  UC_LTO_JOBS                    = auto
```
and:
```
[BuildOptions]
# MultiArchUefiPkg (x86 emulation) build options
  *_*_*_CC_FLAGS                       = -DDISABLE_NEW_DEPRECATED_INTERFACES
!if "$(ON_PRIVATE_STACK)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_ON_PRIVATE_STACK
!endif
!if "$(WRAPPED_ENTRY_POINTS)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_WRAPPED_ENTRY_POINTS
!endif    
!if "$(CHECK_ORPHAN_CONTEXTS)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_CHECK_ORPHAN_CONTEXTS
!endif
!if "$(EMU_TIMEOUT_NONE)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_EMU_TIMEOUT_NONE    
!endif
!if "$(SUPPORTS_X64_BINS)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_SUPPORTS_X64_BINS
!endif
!if "$(EMU_X64_RAZ_WI_PIO)" == "YES"
  *_*_*_CC_FLAGS                       = -DMAU_EMU_X64_RAZ_WI_PIO
!endif
```

But then during boot I get an error "Unimplemented x86_uc_init!" followed by a synchronous exception.

Also, Emulator.dsc includes unicorn/efi/UnicornPkg.dsc.inc - is that something other platforms should be including too?

**Comment by andreiw** [comment]
Sorry, This should be fixed now.

See https://github.com/intel/MultiArchUefiPkg/blob/main/Docs/Building.md#bundled-firmware-builds

In short, the suggested mechanism now is to a) build the driver separately b) take the driver into your UEFI build as a binary (not as source). See https://github.com/intel/MultiArchUefiPkg/blob/main/Docs/BinaryIncluded/0002-ArmVirtPkg-bundle-MultiArchUefiPkg-driver-as-a-bin.patch. You can still choose to build the emulator from source as part of firmware builds, it's just not recommended - see https://github.com/intel/MultiArchUefiPkg/blob/main/Docs/DirectlyIncluded/0002-ArmVirtPkg-bundle-MultiArchUefiPkg-driver.patch.

**Comment by andreiw** [comment]
It should be obvious from the building doc, but you have to build the driver yourself (i.e. see quick start). This repo isn't going to provide binaries (but it's a task to get them into edk2-non-osi...).

Let me know if that solves things on your end.

**Comment by ghost** [comment]
Thanks, that did solve things!
